[bird]
status = 1
name = "北大青鸟"
logo_type = "oneToOne"
logo_url = "https://jmy-pic.baidu.com/0/pic/49687877_810184561_-193613646.png" 
logo_name = "logo.jpg"
slogan = "学IT 好工作 就读北大青鸟"
serviceScope = "软件开发，网络工程，AI，电商，python，UI设计等就业技能"
advantage = ["3-21天免费试学体验","0基础入学快速转行","实战教学项目贯穿","入学签订就业协议","合作企业推荐就业","学历技能双重学习"]
brandStory = """北大青鸟依托自有研究院优质雄厚的教育资源和背景，秉承“教育改变生活”的发展理念，一直致力于培养中国IT技能型紧缺人才。
北大青鸟在中国职业教育发展的重要历史阶段，始终引领行业发展方向，并以完善的标准化管理为依托实现了体系的规模化发展。当前，北大青鸟职业教育的200余家授权培训中心遍布全国60多个重要城市，全国合作院校超过800所，同20000余家知名企业建立了战珞合作伙伴关系，累计培养和输送100万IT互联网职业化人才进入IT行业，得到了社会各界广泛的认可。"""
image = ['https://jmy-pic.baidu.com/0/pic/639392699_-81827528_148622732.png',"https://jmy-pic.baidu.com/0/pic/1206833294_1841087126_116864439.jpg"]



[kawa]
status = 1
name = "嘉华金蛛"
logo_type = "oneToOne"
logo_url = "https://jmy-pic.baidu.com/0/pic/937631491_-1446478894_-320805632.jpg" 
logo_name = "logo.jpg"
slogan = "学IT 好工作 就读嘉华金蛛"
serviceScope = "软件开发，网络工程，AI，电商，python，UI设计等就业技能"
advantage = ["3-21天免费试学体验","0基础入学快速转行","实战教学项目贯穿","入学签订就业协议","合作企业推荐就业","学历技能双重学习"]
brandStory = """嘉华金蛛依托自有研究院优质雄厚的教育资源和背景，秉承“教育改变生活”的发展理念，一直致力于培养中国IT技能型紧缺人才。
嘉华金蛛在中国职业教育发展的重要历史阶段，始终引领行业发展方向，并以完善的标准化管理为依托实现了体系的规模化发展。当前，嘉华金蛛职业教育的200余家授权培训中心遍布全国60多个重要城市，全国合作院校超过800所，同20000余家知名企业建立了战珞合作伙伴关系，累计培养和输送100万IT互联网职业化人才进入IT行业，得到了社会各界广泛的认可。"""
image = ['https://jmy-pic.baidu.com/0/pic/-1253400501_-1768845201_-1589793518.png',"https://jmy-pic.baidu.com/0/pic/1206833294_1841087126_116864439.jpg"]


[jinzhu]
status = 1
name = "金蛛教育"
logo_type = "oneToOne"
logo_url = "https://jmy-pic.baidu.com/0/pic/937631491_-1446478894_-320805632.jpg" 
logo_name = "logo.jpg"
slogan = "学IT 好工作 就读金蛛教育"
serviceScope = "软件开发，网络工程，AI，电商，python，UI设计等就业技能"
advantage = ["3-21天免费试学体验","0基础入学快速转行","实战教学项目贯穿","入学签订就业协议","合作企业推荐就业","学历技能双重学习"]
brandStory = """金蛛教育依托自有研究院优质雄厚的教育资源和背景，秉承“教育改变生活”的发展理念，一直致力于培养中国IT技能型紧缺人才。
金蛛教育在中国职业教育发展的重要历史阶段，始终引领行业发展方向，并以完善的标准化管理为依托实现了体系的规模化发展。当前，金蛛教育职业教育的200余家授权培训中心遍布全国60多个重要城市，全国合作院校超过800所，同20000余家知名企业建立了战珞合作伙伴关系，累计培养和输送100万IT互联网职业化人才进入IT行业，得到了社会各界广泛的认可。"""
image = ['https://jmy-pic.baidu.com/0/pic/155185386_322269125_-1153014116.png',"https://jmy-pic.baidu.com/0/pic/1206833294_1841087126_116864439.jpg"]
